-- B: saldo prepago NATIVO del CAF (deja de depender del Medidor para el saldo).
-- Libro append-only: balance = sum(credit) - sum(debit). El Medidor solo MIDE consumo.
CREATE TABLE IF NOT EXISTS prepaid_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    kind TEXT NOT NULL CHECK (kind IN ('credit','debit')),
    amount_cents BIGINT NOT NULL CHECK (amount_cents > 0),
    service_code TEXT, units BIGINT,
    source TEXT NOT NULL, idempotency_key TEXT, meta JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_prepaid_ledger_idem ON prepaid_ledger (client_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_prepaid_ledger_client ON prepaid_ledger (client_id);
DROP TRIGGER IF EXISTS prepaid_ledger_no_delete ON prepaid_ledger;
CREATE TRIGGER prepaid_ledger_no_delete BEFORE UPDATE OR DELETE ON prepaid_ledger FOR EACH ROW EXECUTE FUNCTION trg_block_update_delete();
CREATE OR REPLACE VIEW v_client_balance AS
SELECT c.id AS client_id, COALESCE(SUM(CASE WHEN l.kind='credit' THEN l.amount_cents WHEN l.kind='debit' THEN -l.amount_cents END),0) AS balance_cents
FROM clients c LEFT JOIN prepaid_ledger l ON l.client_id=c.id GROUP BY c.id;
