-- 031: Capa multi-organizacion (tenancy) para CAF Billing Engine SaaS.
-- F0 ADDITIVO: agrega entidad organizations + organization_id a las tablas de
-- primer nivel, con DEFAULT 1 (org Inovaweb) para NO romper el codigo vivo
-- (que aun no conoce la columna). NO toca logica de cobro ni constraints de code.
-- El DEFAULT se retira en F1 cuando el codigo setee organization_id del contexto.

BEGIN;

CREATE TABLE IF NOT EXISTS organizations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT NOT NULL,
    name        TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT organizations_slug_key UNIQUE (slug),
    CONSTRAINT organizations_status_check CHECK (status IN ('active','suspended','cancelled'))
);

-- Org #1 = Inovaweb: operador de la plataforma + primera org que usa el motor.
INSERT INTO organizations (id, slug, name, status)
VALUES (1, 'inovaweb', 'Inovaweb', 'active')
ON CONFLICT (slug) DO NOTHING;
SELECT setval(pg_get_serial_sequence('organizations','id'), GREATEST((SELECT max(id) FROM organizations),1));

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'clients','users','services','plans','products','promotions','api_keys',
    'subscriptions','invoices','payments','adjustments','price_catalog','prepaid_ledger'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1', t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_%s_org ON %I(organization_id)', t, t);
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = t || '_organization_id_fkey') THEN
      EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (organization_id) REFERENCES organizations(id)',
                     t, t || '_organization_id_fkey');
    END IF;
  END LOOP;
END $$;

COMMIT;
