-- 033: proveedores de correo por organización (y opcionalmente por cliente).
-- Tabla canónica `email_providers`: configuración de envío de email a nivel org
-- (client_id NULL) o de un cliente específico (client_id con valor). Soporta
-- 'microsoft', 'gmail' y 'smtp'. El secreto (api_key/app_password/refresh_token/
-- client_secret según el proveedor) viaja SIEMPRE cifrado en `secret_encrypted`
-- vía app.core.crypto.encrypt_secret — NUNCA en claro.
-- Additivo, idempotente y transaccional: solo CREATE TABLE + índices (sin seeds).

BEGIN;

CREATE TABLE IF NOT EXISTS email_providers (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id  BIGINT  NOT NULL REFERENCES organizations(id),
  client_id        BIGINT  REFERENCES clients(id),
  provider         TEXT    NOT NULL CHECK (provider IN ('microsoft','gmail','smtp')),
  display_name     TEXT,
  from_email       TEXT    NOT NULL,
  from_name        TEXT,
  smtp_host        TEXT,
  smtp_port        INTEGER,
  smtp_user        TEXT,
  secret_encrypted TEXT,
  is_default       BOOLEAN NOT NULL DEFAULT false,
  is_active        BOOLEAN NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_providers_org    ON email_providers (organization_id);
CREATE INDEX IF NOT EXISTS idx_email_providers_client ON email_providers (client_id);

COMMIT;
