-- 036: distribuidores + enlace de promociones a distribuidor.
-- Cada código de promoción (promotions) se asocia a un distribuidor; el código
-- lleva un descuento en % (promotions.discount_pct) que se aplica al contratar
-- (self-service). Por ahora del distribuidor se da de alta solo el nombre.
-- Additivo, idempotente, transaccional.

BEGIN;

CREATE TABLE IF NOT EXISTS distributors (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id  BIGINT  NOT NULL DEFAULT 1 REFERENCES organizations(id),
  name             TEXT    NOT NULL,
  external_ref     TEXT,                          -- ID externo del distribuidor (futuro)
  is_active        BOOLEAN NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_distributors_org ON distributors (organization_id);

ALTER TABLE promotions
  ADD COLUMN IF NOT EXISTS distributor_id BIGINT REFERENCES distributors(id);
CREATE INDEX IF NOT EXISTS idx_promotions_distributor ON promotions (distributor_id);

COMMIT;
